using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using ExcelDna.Integration;
using ExcelDna.Integration.CustomUI;
using Microsoft.Office.Interop.Excel;
using TSL.UI;
using Application = Microsoft.Office.Interop.Excel.Application;

namespace TSL.AddIn
{
    /// <summary>
    /// Office IRibbonExtensibility COM interface.
    /// Defined locally to avoid depending on the Office PIA (office.dll).
    /// </summary>
    [ComImport]
    [Guid("000C0396-0000-0000-C000-000000000046")]
    [InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    internal interface IRibbonExtensibility
    {
        [DispId(1)]
        string GetCustomUI(string ribbonId);
    }

    /// <summary>
    /// Ribbon controller for the "Time Series Lab" tab.
    /// Uses ExcelComAddIn (not ExcelRibbon) to avoid Excel-DNA auto-discovery,
    /// which would register the ribbon before external COM add-ins (e.g. Acrobat).
    /// Manually registered via ExcelComAddInHelper.LoadComAddIn() in AddIn.AutoOpen().
    /// </summary>
    [ComVisible(true)]
    public class Ribbon : ExcelComAddIn, IRibbonExtensibility
    {
        private ExcelDna.Integration.CustomUI.IRibbonUI _ribbonUi;

        // Technique id -> sample dataset file + sheet name. Populated from
        // the catalog + a curated mapping of each technique to the most
        // appropriate data. Drives the per-technique Sample Data submenu
        // (one entry per technique, grouped by category).
        // GENERATED by tools/.../generate_sample_menu.py — keep the
        // entries in sync with the Ribbon XML if you add new techniques.
        private static readonly System.Collections.Generic.Dictionary<string, (string CsvFileName, string SheetName)>
            _sampleDatasetByTechnique =
                new System.Collections.Generic.Dictionary<string, (string, string)>(System.StringComparer.OrdinalIgnoreCase)
                {
                    { "stl_decompose", ("airline_passengers.csv", "Airline Passengers") },
                    { "classical_decompose", ("airline_passengers.csv", "Airline Passengers") },
                    { "mstl_decompose", ("airline_passengers.csv", "Airline Passengers") },
                    { "x13_seasonal_adjust", ("nonfarm_payroll_nsa.csv", "Payrolls NSA") },
                    { "ets_hw", ("airline_passengers.csv", "Airline Passengers") },
                    { "theta_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "arima", ("real_gdp.csv", "Real GDP") },
                    { "sarima", ("airline_passengers.csv", "Airline Passengers") },
                    { "auto_arima", ("airline_passengers.csv", "Airline Passengers") },
                    { "arimax_sarimax", ("macro_var.csv", "Macro VAR") },
                    { "transfer_function", ("macro_var.csv", "Macro VAR") },
                    { "intermittent_demand", ("intermittent_demand.csv", "Intermittent Demand") },
                    { "adf_test", ("real_gdp.csv", "Real GDP") },
                    { "kpss_test", ("real_gdp.csv", "Real GDP") },
                    { "pp_test", ("real_gdp.csv", "Real GDP") },
                    { "var", ("macro_var.csv", "Macro VAR") },
                    { "vecm", ("treasury_yields.csv", "Treasury Yields") },
                    { "johansen_cointegration", ("treasury_yields.csv", "Treasury Yields") },
                    { "bvar", ("macro_var.csv", "Macro VAR") },
                    { "dynamic_factor_model", ("dfm_coincident.csv", "DFM Data") },
                    { "pca_analysis", ("treasury_yields.csv", "Treasury Yields") },
                    { "forecast_reconciliation", ("macro_var.csv", "Macro VAR") },
                    { "local_level", ("nile_river.csv", "Nile River") },
                    { "local_linear_trend", ("airline_passengers.csv", "Airline Passengers") },
                    { "structural_ts", ("airline_passengers.csv", "Airline Passengers") },
                    { "particle_filter", ("nile_river.csv", "Nile River") },
                    { "markov_switching", ("real_gdp.csv", "Real GDP") },
                    { "hmm", ("real_gdp.csv", "Real GDP") },
                    { "tar_setar", ("real_gdp.csv", "Real GDP") },
                    { "star", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "nar_narx", ("macro_var.csv", "Macro VAR") },
                    { "garch", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "gjr_garch", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "egarch", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "stochastic_volatility", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "har_rv", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "evt_pot_gpd", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "caviar_quantile_dynamics", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "fft_spectrum", ("sunspots.csv", "Sunspots") },
                    { "periodogram_spectral_density", ("sunspots.csv", "Sunspots") },
                    { "lomb_scargle", ("sunspots.csv", "Sunspots") },
                    { "wavelet_transform", ("sunspots.csv", "Sunspots") },
                    { "wavelet_coherence_phase_lag", ("macro_var.csv", "Macro VAR") },
                    { "ssa", ("sunspots.csv", "Sunspots") },
                    { "emd_hht", ("sunspots.csv", "Sunspots") },
                    { "pelt_change_points", ("nile_river.csv", "Nile River") },
                    { "bocpd", ("nile_river.csv", "Nile River") },
                    { "cusum_page_hinkley", ("nile_river.csv", "Nile River") },
                    { "stl_esd_anomaly", ("airline_passengers.csv", "Airline Passengers") },
                    { "intervention_analysis", ("nile_river.csv", "Nile River") },
                    { "granger_causality", ("macro_var.csv", "Macro VAR") },
                    { "cross_correlation_lag", ("macro_var.csv", "Macro VAR") },
                    { "prewhitened_ccf_lag", ("macro_var.csv", "Macro VAR") },
                    { "gcc_phat_delay", ("macro_var.csv", "Macro VAR") },
                    { "rolling_ccf_lag", ("macro_var.csv", "Macro VAR") },
                    { "dtw_alignment_lag", ("macro_var.csv", "Macro VAR") },
                    { "rolling_origin_cv", ("real_gdp.csv", "Real GDP") },
                    { "block_bootstrap", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "conformal_intervals", ("real_gdp.csv", "Real GDP") },
                    { "forecast_combination", ("real_gdp.csv", "Real GDP") },
                    { "robust_estimators", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "kalman_imputation", ("airline_passengers.csv", "Airline Passengers") },
                    { "loess_interpolation", ("airline_passengers.csv", "Airline Passengers") },
                    { "denton_chowlin_disaggregation", ("gdp_ip_disaggregation.csv", "GDP + IP") },
                    { "gradient_boosting_forecast", ("macro_var.csv", "Macro VAR") },
                    { "quantile_regression", ("real_gdp.csv", "Real GDP") },
                    { "gaussian_process_forecast", ("real_gdp.csv", "Real GDP") },
                    { "lstm_gru_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "tcn_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "nbeats_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "transformer_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "prophet_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "random_forest_forecast", ("macro_var.csv", "Macro VAR") },
                    { "xgboost_forecast", ("macro_var.csv", "Macro VAR") },
                    { "svr_forecast", ("real_gdp.csv", "Real GDP") },
                    { "autoencoder_anomaly", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "nhits_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "echo_state_network", ("sunspots.csv", "Sunspots") },
                    { "lightgbm_forecast", ("macro_var.csv", "Macro VAR") },
                };

        public string GetCustomUI(string ribbonId)
        {
            return RibbonXml.GetXml();
        }

        #region Callbacks

        public void OnRibbonLoad(IRibbonUI ribbonUi)
        {
            _ribbonUi = ribbonUi;
            s_ribbonUi = ribbonUi;
        }

        // The ribbon, for refreshes that start outside a ribbon callback (A2 U7: the task
        // pane's Settings view changes the preset).
        private static IRibbonUI s_ribbonUi;

        /// <summary>
        /// Redraw the Preset menu's label and check marks after the preset changed elsewhere
        /// (the task pane's Settings view). Cosmetic: a failure is logged only.
        /// </summary>
        internal static void RefreshPresetControls()
        {
            try
            {
                s_ribbonUi?.InvalidateControl("menuPreset");
                s_ribbonUi?.InvalidateControl("btnPresetFast");
                s_ribbonUi?.InvalidateControl("btnPresetBalanced");
                s_ribbonUi?.InvalidateControl("btnPresetThorough");
            }
            catch (Exception ex)
            {
                Logger.Info($"Could not refresh the Preset menu: {ex.Message}");
            }
        }

        // ── Quick Actions ──────────────────────────────────────────────

        // ── Quick Actions: open the Run view, filled, and wait ─────────
        // Each ribbon Quick Action skips the Explorer description page and
        // calls RunTechnique, which opens the task pane on the Run view for
        // its technique, filled from the current Excel selection (series
        // preview, time index, parameters), and WAITS: nothing runs until the
        // user clicks Run in the pane or on the ribbon (A2 K1; the
        // configure-then-run contract since f5ade12).

        // Multivariate / system modeling
        public void OnVar(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("var");
        }

        public void OnPcaAnalysis(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("pca_analysis");
        }

        public void OnDynamicFactorModel(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("dynamic_factor_model");
        }

        public void OnCointegration(IRibbonControl control)
        {
            // VECM includes the Johansen cointegration test as part of
            // the fit, so landing here gives both the equilibrium test
            // and the error-correction model in one shot.
            TaskPaneManager.RunTechnique("vecm");
        }

        // Univariate workhorses + causality/forecasting
        public void OnGrangerCausality(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("granger_causality");
        }

        public void OnRollingCcf(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("rolling_ccf_lag");
        }

        public void OnSeasonalAdjustment(IRibbonControl control)
        {
            // STL is the default — robust, handles outliers, no external
            // binary required. X-13 ARIMA-SEATS is available via the
            // Technique Explorer or Sample Data menu for the BLS/BEA
            // gold-standard seasonal adjustment.
            TaskPaneManager.RunTechnique("stl_decompose");
        }

        public void OnForecast(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("auto_arima");
        }

        public void OnProphet(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("prophet_forecast");
        }

        public void OnConformal(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("conformal_intervals");
        }

        // ── Bond Yield Forecast (BYF Integration Session 3) ──────────
        // A menu with two items (RibbonXml.cs menuBondYieldForecast):
        //   - "Open Input Template" = OnBondYieldForecastOpenTemplate
        //   - "Run Bond Yield Forecast" = OnBondYieldForecastRun

        public void OnBondYieldForecastRun(IRibbonControl control)
        {
            // Bond Yield Forecast consumes a 3-sheet xlsx workbook
            // (BondYield_Macro / BondYield_Yields / BondYield_Projections)
            // referenced via ctx.params["input_workbook"], NOT the standard
            // ctx.series cell-selection contract.
            //
            // CONFIGURE-then-run: open the Run view with the curated parameters
            // (scenario / horizon / chain length / prior tightness) pre-filled
            // and editable. The user reviews/edits, then clicks Run IN THE VIEW.
            // The Run button routes to TaskPaneManager.OnWorkbookRunRequested,
            // which takes the workbook the Run view was set up for (A2 B7: the
            // active workbook when it opened, else the active workbook at the
            // first Run), SaveCopyAs-es a local %TEMP% copy (off OneDrive,
            // captures unsaved edits — the d923c6a fix), and dispatches. The
            // "no workbook open" guard lives at Run-click, not at view-open.
            try
            {
                TaskPaneManager.OpenBondYieldForecastConfig();
            }
            catch (Exception ex)
            {
                ReportOpenFailure("Bond Yield Forecast", ex);
            }
        }

        public void OnBondYieldForecastOpenTemplate(IRibbonControl control)
        {
            OpenTemplateWorkingCopy("Bond Yield Forecast", "Bond Yield Forecast input template", "BondYield_input",
                "engine", "techniques", "bond_yield_forecast", "resources", "templates",
                "bond_yield_forecast_input_template.xlsx");
        }

        // ── Breakeven Payrolls (Bespoke member #2; workbook-input) ──────
        public void OnBreakevenPayrollRun(IRibbonControl control)
        {
            // Workbook-input technique (mirrors Bond Yield Forecast): CONFIGURE-
            // then-run. Open the Run view; the Run button routes to the shared
            // TaskPaneManager.OnWorkbookRunRequested, which takes the workbook the
            // Run view was set up for (A2 B7), SaveCopyAs-es a %TEMP% copy, and
            // dispatches. The scenario
            // and data live in the workbook (scenario_inputs + baked tabs).
            try
            {
                TaskPaneManager.OpenBreakevenPayrollConfig();
            }
            catch (Exception ex)
            {
                ReportOpenFailure("Breakeven Payrolls", ex);
            }
        }

        public void OnBreakevenPayrollOpenTemplate(IRibbonControl control)
        {
            OpenTemplateWorkingCopy("Breakeven Payrolls", "Breakeven Payrolls input template", "Breakeven_Payrolls_input",
                "engine", "techniques", "breakeven_payroll", "resources", "templates",
                "breakeven_payroll_input_template.xlsx");
        }

        // ── Kronos Forecast (Bespoke member #3; EXPERIMENTAL) ──────────────
        // Clones the Breakeven Payrolls invocation mechanics exactly: open a
        // WORKING COPY of the bundled template (never the bundled file in
        // place); Run routes configure-then-run through the shared
        // workbook-input dispatch.

        public void OnKronosOpenTemplate(IRibbonControl control)
        {
            // The lineage-verified 250-day IEF example + parameter cells.
            OpenTemplateWorkingCopy("Kronos Forecast", "Kronos Forecast input template", "Kronos_Forecast_input",
                "engine", "techniques", "kronos_forecast", "resources", "templates",
                "kronos_forecast_input_template.xlsx");
        }

        // Kronos needs its own torch environment, which exists only where it was
        // built (the owner's machine). Hide Bespoke > Kronos Forecast wherever it is
        // absent, by the test the Technique Explorer shares (KronosEnvironment).
        // Evaluated when the ribbon loads.
        public bool OnKronosGetVisible(IRibbonControl control) => KronosEnvironment.IsAvailable();

        public void OnKronosRun(IRibbonControl control)
        {
            try
            {
                TaskPaneManager.OpenKronosConfig();
            }
            catch (Exception ex)
            {
                ReportOpenFailure("Kronos Forecast", ex);
            }
        }

        /// <summary>
        /// A Bespoke tool's Run view could not be opened in the task pane (house dialog;
        /// <paramref name="tool"/> is its Bespoke menu label). Also used when the Technique
        /// Explorer's Configure &amp; Run opens a Bespoke tool.
        /// </summary>
        internal static void ReportOpenFailure(string tool, Exception ex)
        {
            Logger.Error($"Opening {tool} in the task pane failed.", ex);
            HouseDialog.ShowHouseAlert(
                $"Time Series Lab could not open {tool} in the task pane. Nothing was changed.\n\n" +
                HouseDialog.ErrorBlock(ex.Message) + "\n\n" +
                "Try again. If this message returns, tell Matthew Hornbach.",
                HouseDialog.Title(tool), isError: true);
        }

        /// <summary>
        /// Bespoke &gt; &lt;tool&gt; &gt; Open Input Template. Opens a WORKING COPY, never
        /// the bundled template in place: the user's edits + Excel AutoSave must NOT write
        /// back into the shipped template (which would ship a stale default to the next
        /// user). The bundled file (under the add-in's layout root, AddInLayout) is only ever
        /// a File.Copy source. Every failure is reported through the house dialog: a missing
        /// template, an error before the step is queued, and an error inside the queued copy
        /// and open (A2 N12 - those were not caught before), each with what it left behind.
        /// </summary>
        private void OpenTemplateWorkingCopy(string tool, string templateName, string baseName,
            params string[] relative)
        {
            string templatePath = null;
            try
            {
                templatePath = AddInLayout.FindFile(out var tried, relative);
                if (templatePath == null)
                {
                    AddInLayout.ReportMissing(tool, templateName, tried);
                    return;
                }

                var bundled = templatePath;
                ExcelAsyncUtil.QueueAsMacro(() =>
                {
                    string workingPath = null;
                    try
                    {
                        var app = (Application)ExcelDnaUtil.Application;
                        workingPath = CreateTemplateWorkingCopy(bundled, baseName);
                        app.Workbooks.Open(workingPath, ReadOnly: false);
                    }
                    catch (Exception ex)
                    {
                        ReportTemplateFailure(tool, templateName, bundled, workingPath, ex, copying: true);
                        return;
                    }
                    RestoreTab();
                });
            }
            catch (Exception ex)
            {
                ReportTemplateFailure(tool, templateName, templatePath, null, ex, copying: false);
            }
        }

        /// <summary>
        /// <paramref name="copying"/>: the failure was in the queued copy-and-open step (so,
        /// with no working copy yet, in making the copy); otherwise before it was queued.
        /// </summary>
        private static void ReportTemplateFailure(string tool, string templateName, string templatePath,
            string workingPath, Exception ex, bool copying)
        {
            Logger.Error($"{tool} > Open Input Template failed (template {templatePath ?? "(not resolved)"}, " +
                         $"working copy {workingPath ?? "(none)"}).", ex);
            var template = templatePath != null ? "The template:\n" + HouseDialog.Indent(templatePath) + "\n\n" : "";
            string message;
            if (workingPath == null && copying)
            {
                message = $"Time Series Lab could not make a working copy of the {templateName}. Nothing was changed.\n\n" +
                          template +
                          "The working copy was to go in:\n" + HouseDialog.Indent(TemplateWorkingFolder()) + "\n\n" +
                          HouseDialog.ErrorBlock(ex.Message) + "\n\n" +
                          "Try again. If this message returns, tell Matthew Hornbach.";
            }
            else if (workingPath == null)
            {
                message = $"Time Series Lab could not open the {templateName}. Nothing was changed.\n\n" +
                          template +
                          HouseDialog.ErrorBlock(ex.Message) + "\n\n" +
                          "Try again. If this message returns, tell Matthew Hornbach.";
            }
            else
            {
                message = $"Time Series Lab made a working copy of the {templateName} but could not open it. " +
                          "The working copy was kept:\n" + HouseDialog.Indent(workingPath) + "\n\n" +
                          HouseDialog.ErrorBlock(ex.Message) + "\n\n" +
                          "Open the working copy with File > Open, or try again. " +
                          "If this message returns, tell Matthew Hornbach.";
            }
            HouseDialog.ShowHouseAlert(message, HouseDialog.Title(tool), isError: true);
        }

        /// <summary>
        /// Opening or activating a workbook resets the ribbon to the Home tab; bring the
        /// Time Series Lab tab back so the user stays where they were. Cosmetic: a failure
        /// is logged, never reported as a failed action.
        /// </summary>
        private void RestoreTab()
        {
            try { _ribbonUi?.ActivateTabQ("tslTab", "TimeSeriesLab"); }
            catch (Exception ex) { Logger.Info($"Could not return to the Time Series Lab tab: {ex.Message}"); }
        }

        /// <summary>
        /// Copy a bundled input template to a fresh, user-reachable WORKING COPY
        /// and return its path. Shared by both workbook-input techniques' "Open
        /// Input Template" so the user always edits a COPY — the bundled template
        /// is only ever a File.Copy source and can never be contaminated by an
        /// edit + Excel AutoSave (the template-side analogue of the separate-file
        /// output's input-never-mutated guarantee). Lands in a persistent,
        /// findable location (Documents\Time Series Lab) suited to the
        /// user-updatable operating model.
        /// </summary>
        private string CreateTemplateWorkingCopy(string bundledTemplatePath, string baseName)
        {
            var dir = TemplateWorkingFolder();
            Directory.CreateDirectory(dir);

            var stamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            var path = Path.Combine(dir, $"{baseName}_working_{stamp}.xlsx");
            for (int n = 1; File.Exists(path); n++)
                path = Path.Combine(dir, $"{baseName}_working_{stamp}_{n}.xlsx");

            File.Copy(bundledTemplatePath, path);
            return path;
        }

        /// <summary>Documents\Time Series Lab: where template working copies go.</summary>
        private static string TemplateWorkingFolder() =>
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "Time Series Lab");

        // Regime / volatility / state-space
        public void OnMarkovSwitching(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("markov_switching");
        }

        public void OnChangePoint(IRibbonControl control)
        {
            // PELT is the offline change-point workhorse. BOCPD (online)
            // is available via the Technique Explorer for streaming use.
            TaskPaneManager.RunTechnique("pelt_change_points");
        }

        public void OnGarch(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("garch");
        }

        public void OnStructuralTS(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("structural_ts");
        }

        // ── Legacy Quick Action handlers ──────────────────────────────
        // The Lead-Lag Finder and Anomaly Scan buttons were removed from
        // the ribbon in the macro-strategist reorg (both techniques are
        // still available via the Technique Explorer and Sample Data
        // menu). Handler stubs remain so any saved macros or legacy
        // workflows referencing them by name keep working.
        public void OnLeadLagFinder(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("prewhitened_ccf_lag");
        }

        public void OnAnomalyScan(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("stl_esd_anomaly");
        }

        // ── Explore ────────────────────────────────────────────────────

        public void OnTechniqueExplorer(IRibbonControl control)
        {
            TaskPaneManager.ShowExplorer();
        }

        public void OnRecommenderWizard(IRibbonControl control)
        {
            TaskPaneManager.ShowRecommender();
        }

        public void OnRecommenderGoal(IRibbonControl control)
        {
            TaskPaneManager.ShowRecommenderWithGoal(control.Tag);
        }

        public void OnExplorerCategory(IRibbonControl control)
        {
            TaskPaneManager.ShowExplorerWithCategory(control.Tag);
        }

        public void OnDataReadiness(IRibbonControl control)
        {
            TaskPaneManager.ShowDataReadiness();
        }

        // ── Run ────────────────────────────────────────────────────────

        /// <summary>
        /// Menu-level label for the Preset button. Shows "Preset: <current>"
        /// so the user sees their active selection without having to open the
        /// menu.
        /// </summary>
        public string OnPresetGetLabel(IRibbonControl control)
        {
            var preset = AddIn.Settings?.GetGlobalPreset() ?? "Balanced";
            return $"Preset: {preset}";
        }

        /// <summary>
        /// Returns true for the toggleButton whose tag matches the currently
        /// active preset. Excel renders the matching item with a check mark
        /// in the menu (just like "None (House Default)" in the Axes Grid
        /// reference menu).
        /// </summary>
        public bool OnPresetGetPressed(IRibbonControl control)
        {
            var current = AddIn.Settings?.GetGlobalPreset() ?? "Balanced";
            return string.Equals(control?.Tag, current, StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Click handler for the three preset toggleButtons. Pulls the
        /// preset name from the control's Tag attribute.
        /// </summary>
        public void OnPresetMenuClick(IRibbonControl control, bool pressed)
        {
            var preset = control?.Tag;
            if (string.IsNullOrEmpty(preset)) return;

            AddIn.Settings?.SetGlobalPreset(preset);
            TaskPaneManager.UpdatePreset(preset);

            // Refresh the menu button label and the check marks on the
            // three toggle buttons so the UI reflects the new selection.
            _ribbonUi?.InvalidateControl("menuPreset");
            _ribbonUi?.InvalidateControl("btnPresetFast");
            _ribbonUi?.InvalidateControl("btnPresetBalanced");
            _ribbonUi?.InvalidateControl("btnPresetThorough");
        }

        public void OnRun(IRibbonControl control)
        {
            TaskPaneManager.RunCurrent();
        }

        public void OnCancel(IRibbonControl control)
        {
            TaskPaneManager.CancelFromRibbon();
        }

        public void OnRerunThorough(IRibbonControl control)
        {
            TriggerManager.IncrementTrigger();
            _ribbonUi?.Invalidate();
        }

        public void OnSettings(IRibbonControl control)
        {
            TaskPaneManager.ShowSettings();
        }

        // ── Help ───────────────────────────────────────────────────────

        public void OnUdfGuide(IRibbonControl control)
        {
            TaskPaneManager.ShowUdfBrowser();
        }

        // Help > User Guide (the split button's label is the area of every message below).
        private const string UserGuideArea = "User Guide";

        /// <summary>The generator's command line, indented, with the script's full path (development tree only).</summary>
        private static string GenerateGuideCommand() =>
            HouseDialog.Indent($"python \"{Path.Combine(AddInLayout.Root ?? "", "tools", "generate_user_guide.py")}\"");

        public void OnOpenUserGuide(IRibbonControl control)
        {
            var guidePath = AddInLayout.FindFile(out var tried, "docs", "TimeSeriesLab_UserGuide.docx");

            if (guidePath != null)
            {
                OpenDocument(UserGuideArea, "User Guide (Word document)", guidePath);
            }
            else if (AddInLayout.Kind != LayoutKind.Development)
            {
                // Installed: the guide ships in docs\ - name the path; never offer to
                // run a development script on a colleague's PC.
                AddInLayout.ReportMissing(UserGuideArea, "User Guide (Word document)", tried);
            }
            else
            {
                // Development tree only: offer to generate it.
                var generate = HouseDialog.ShowConfirm(
                    "The User Guide (Word document) has not been generated in this development tree.\n\n" +
                    "Time Series Lab can run its generator now. It needs Python with python-docx.\n\n" +
                    "The command:\n" + GenerateGuideCommand() + "\n\n" +
                    "Generate = run the generator, then open the guide\n" +
                    "Cancel = do not generate the guide now",
                    HouseDialog.Title(UserGuideArea), "Generate");
                if (generate)
                    GenerateAndOpenUserGuide();
            }
        }

        /// <summary>Development tree only: run tools\generate_user_guide.py, then open the Word guide.</summary>
        private static void GenerateAndOpenUserGuide()
        {
            var title = HouseDialog.Title(UserGuideArea);
            var projectRoot = AddInLayout.Root;
            var script = Path.Combine(projectRoot, "tools", "generate_user_guide.py");
            var generated = Path.Combine(projectRoot, "docs", "TimeSeriesLab_UserGuide.docx");

            if (!File.Exists(script))
            {
                HouseDialog.ShowHouseAlert(
                    "Time Series Lab could not find the User Guide generator. Nothing was generated.\n\n" +
                    "It looked here:\n" + HouseDialog.Indent(script) + "\n\n" +
                    "Restore the generator script at the path above, then click " +
                    "Help > User Guide > Open as Word Document again.",
                    title, isError: true);
                return;
            }

            bool finished;
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "python",
                    Arguments = $"\"{script}\"",
                    WorkingDirectory = projectRoot,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                };
                using (var proc = Process.Start(psi))
                {
                    finished = proc != null && proc.WaitForExit(30000);
                }
            }
            catch (Exception ex)
            {
                Logger.Error("Running the User Guide generator failed.", ex);
                HouseDialog.ShowHouseAlert(
                    "Time Series Lab could not run the User Guide generator. Nothing was generated.\n\n" +
                    HouseDialog.ErrorBlock(ex.Message) + "\n\n" +
                    "Check that Python is on the PATH, then try again.",
                    title, isError: true);
                return;
            }

            if (File.Exists(generated))
            {
                OpenDocument(UserGuideArea, "User Guide (Word document)", generated);
                return;
            }

            HouseDialog.ShowHouseAlert(
                (finished
                    ? "The User Guide generator finished, but the Word document was not created. Nothing was opened.\n\n"
                    : "The User Guide generator did not finish within 30 seconds, so nothing was opened. " +
                      "It may still be running.\n\n") +
                "Expected file:\n" + HouseDialog.Indent(generated) + "\n\n" +
                (finished
                    ? "Run the generator from a command prompt to see its output:\n" + GenerateGuideCommand()
                    : "Wait, then click Help > User Guide > Open as Word Document again."),
                title, isError: true);
        }

        public void OnOpenUserGuideHtml(IRibbonControl control)
        {
            var guidePath = AddInLayout.FindFile(out var tried, "docs", "TimeSeriesLab_UserGuide.html");

            if (guidePath != null)
            {
                OpenDocument(UserGuideArea, "User Guide (web page)", guidePath);
            }
            else if (AddInLayout.Kind == LayoutKind.Development)
            {
                AddInLayout.ReportMissing(UserGuideArea, "User Guide (web page)", tried,
                    "Generate it in this development tree with:\n" + GenerateGuideCommand());
            }
            else
            {
                AddInLayout.ReportMissing(UserGuideArea, "User Guide (web page)", tried);
            }
        }

        /// <summary>
        /// Open a document with its Windows default program; a failure (e.g. no program
        /// registered for it) is reported, not dropped.
        /// </summary>
        private static void OpenDocument(string area, string what, string path)
        {
            try
            {
                Process.Start(path);
            }
            catch (Exception ex)
            {
                Logger.Error($"Opening {path} failed.", ex);
                HouseDialog.ShowHouseAlert(
                    $"Time Series Lab found the {what}, but Windows could not open it. Nothing was changed.\n\n" +
                    "The file:\n" + HouseDialog.Indent(path) + "\n\n" +
                    HouseDialog.ErrorBlock(ex.Message) + "\n\n" +
                    "Open the file from File Explorer. If it still does not open, tell Matthew Hornbach.",
                    HouseDialog.Title(area), isError: true);
            }
        }

        /// <summary>
        /// Single handler for all 81 per-technique sample-data menu entries.
        /// Reads the clicked button's `tag` (the technique id) and looks up
        /// the matching CSV + sheet name in `_sampleDatasetByTechnique`.
        /// Many techniques share the same CSV — that's fine; each technique
        /// gets its own labelled entry, and they all land on a fresh sheet
        /// (unique-ified if the target name already exists).
        /// </summary>
        public void OnSampleDataByTechnique(IRibbonControl control)
        {
            var tid = control?.Tag;
            if (string.IsNullOrEmpty(tid))
            {
                HouseDialog.ShowHouseAlert(
                    "This Sample Data menu item names no technique. Nothing was changed.\n\n" + HouseDialog.TellMatthew,
                    HouseDialog.Title(SampleDataArea), isError: true);
                return;
            }
            if (!_sampleDatasetByTechnique.TryGetValue(tid, out var mapping))
            {
                // The ribbon XML lists a technique the sample-data mapping above lacks.
                HouseDialog.ShowHouseAlert(
                    "This Sample Data menu item names a technique with no sample dataset:\n" +
                    HouseDialog.Indent(tid) + "\n\n" +
                    "Nothing was changed. " + HouseDialog.TellMatthew,
                    HouseDialog.Title(SampleDataArea), isError: true);
                return;
            }
            LoadSampleData(mapping.CsvFileName, mapping.SheetName);
        }

        // Help > Sample Data (the split button's label is the area of every message below).
        private const string SampleDataArea = "Sample Data";

        public void OnSampleDataTreasury(IRibbonControl control)
        {
            LoadSampleData("treasury_yields.csv", "Treasury Yields");
        }

        public void OnSampleDataGdp(IRibbonControl control)
        {
            LoadSampleData("real_gdp.csv", "Real GDP");
        }

        public void OnSampleDataPce(IRibbonControl control)
        {
            LoadSampleData("core_pce.csv", "Core PCE");
        }

        public void OnSampleDataPayrollSa(IRibbonControl control)
        {
            // Total nonfarm payroll employment levels, seasonally adjusted
            // (FRED PAYEMS, in thousands of jobs). Coverage: Jan 1939 -> latest.
            // Levels — not differences — so X-13/STL seasonal decomposition
            // produces the textbook SA series; compute job gains downstream
            // as first differences of the SA column if desired.
            LoadSampleData("nonfarm_payroll_sa.csv", "Payrolls SA");
        }

        public void OnSampleDataPayrollNsa(IRibbonControl control)
        {
            // Total nonfarm payroll employment levels, not seasonally adjusted
            // (FRED PAYNSA, in thousands of jobs). Coverage: Jan 1939 -> latest.
            // Levels series suitable as direct X-13 / STL input.
            LoadSampleData("nonfarm_payroll_nsa.csv", "Payrolls NSA");
        }

        public void OnSampleDataDfm(IRibbonControl control)
        {
            // Stock-Watson (1989) four coincident indicators: the canonical
            // DFM input and the same series NBER uses for business-cycle
            // dating. Industrial Production (INDPRO), Nonfarm Payrolls
            // (PAYEMS), Real Disposable Personal Income ex. Transfers
            // (W875RX1), Real Manufacturing and Trade Sales (CMRMTSPL).
            // Common window: Jan 1967 -> latest (~709 months).
            LoadSampleData("dfm_coincident.csv", "DFM Data");
        }

        private void LoadSampleData(string fileName, string sheetName)
        {
            string csvPath = null;
            try
            {
                // Locate the CSV: <root>\resources\sample_data\<file> under the
                // add-in's layout root (AddInLayout). The pre-C1 installed candidate
                // omitted the resources\ segment, so it could never match (2026-09-29).
                csvPath = AddInLayout.FindFile(out var tried, "resources", "sample_data", fileName);
                if (csvPath == null)
                {
                    AddInLayout.ReportMissing(SampleDataArea, $"sample data file {fileName}", tried);
                    return;
                }

                // Read CSV and write to a new worksheet. A failure inside the queued
                // step is reported with what it left behind (A2 N12).
                var path = csvPath;
                ExcelAsyncUtil.QueueAsMacro(() =>
                {
                    Microsoft.Office.Interop.Excel.Worksheet ws = null;
                    Microsoft.Office.Interop.Excel.Workbook newWorkbook = null;
                    try
                    {
                        // Read the file before touching any workbook: a read failure leaves nothing behind.
                        var lines = File.ReadAllLines(path);

                        var app = (Microsoft.Office.Interop.Excel.Application)ExcelDnaUtil.Application;
                        var wb = app.ActiveWorkbook;
                        if (wb == null)
                        {
                            wb = app.Workbooks.Add();
                            newWorkbook = wb;
                        }
                        ws = (Microsoft.Office.Interop.Excel.Worksheet)wb.Worksheets.Add();

                        // Make the sheet name unique. With per-technique sample
                        // data entries many techniques share a CSV (e.g. STL,
                        // Classical Decomp, ETS, ARIMA, SARIMA, etc. all load
                        // "Airline Passengers"). If the user clicks two such
                        // entries, the second would otherwise fail with Excel's
                        // "sheet name already in use" error.
                        string candidateName = sheetName;
                        int suffix = 2;
                        bool Exists(string n)
                        {
                            foreach (Microsoft.Office.Interop.Excel.Worksheet s in wb.Worksheets)
                                if (string.Equals(s.Name, n, StringComparison.OrdinalIgnoreCase) && s != ws)
                                    return true;
                            return false;
                        }
                        while (Exists(candidateName))
                        {
                            candidateName = $"{sheetName} ({suffix})";
                            suffix++;
                        }
                        ws.Name = candidateName;

                        for (int r = 0; r < lines.Length; r++)
                        {
                            var cells = lines[r].Split(',');
                            for (int c = 0; c < cells.Length; c++)
                            {
                                var val = cells[c].Trim();
                                ((Range)ws.Cells[r + 1, c + 1]).Value2 = val;
                            }
                        }

                        // Auto-fit columns
                        ws.Columns.AutoFit();
                        ws.Activate();
                    }
                    catch (Exception ex)
                    {
                        ReportSampleDataFailure(path, ws, newWorkbook, ex);
                        return;
                    }
                    RestoreTab();
                });
            }
            catch (Exception ex)
            {
                ReportSampleDataFailure(csvPath, null, null, ex);
            }
        }

        /// <summary>
        /// A sample-data load that failed, with what it left: nothing, a new empty workbook
        /// (<paramref name="newWorkbook"/>, made because none was active), or a new sheet that
        /// may be incomplete (in the active workbook or in that new one).
        /// </summary>
        private static void ReportSampleDataFailure(string csvPath,
            Microsoft.Office.Interop.Excel.Worksheet addedSheet,
            Microsoft.Office.Interop.Excel.Workbook newWorkbook, Exception ex)
        {
            string sheetName = null, bookName = null;
            try { sheetName = addedSheet?.Name; } catch { /* the sheet is unreadable */ }
            try { bookName = newWorkbook?.Name; } catch { /* the workbook is unreadable */ }
            Logger.Error($"Loading sample data from {csvPath ?? "(not resolved)"} failed " +
                         $"(sheet added: {sheetName ?? (addedSheet != null ? "(unnamed)" : "none")}, " +
                         $"new workbook: {bookName ?? (newWorkbook != null ? "(unnamed)" : "none")}).", ex);

            var file = csvPath != null ? "The file:\n" + HouseDialog.Indent(csvPath) + "\n\n" : "";
            var error = HouseDialog.ErrorBlock(ex.Message) + "\n\n";
            const string retry = "If this message returns, tell Matthew Hornbach.";
            string message;
            if (newWorkbook != null)
            {
                message = (addedSheet != null
                              ? "Time Series Lab could not finish loading the sample data. No workbook was active, so it " +
                                "opened a new one, and the new sheet in it may be incomplete. The new workbook was not saved:\n"
                              : "Time Series Lab could not load the sample data. No workbook was active, so it opened a new " +
                                "one, which was left empty and unsaved:\n") +
                          HouseDialog.Indent(bookName ?? "(the workbook's name could not be read)") + "\n\n" +
                          file + error +
                          "Close that workbook without saving, then try again. " + retry;
            }
            else if (addedSheet != null)
            {
                message = "Time Series Lab could not finish loading the sample data. " +
                          "A new sheet was added and may be incomplete:\n" +
                          HouseDialog.Indent(sheetName ?? "(the sheet's name could not be read)") + "\n\n" +
                          file + error +
                          "Delete that sheet, then try again. " + retry;
            }
            else
            {
                message = "Time Series Lab could not load the sample data. Nothing was changed.\n\n" +
                          file + error +
                          "Try again. " + retry;
            }
            HouseDialog.ShowHouseAlert(message, HouseDialog.Title(SampleDataArea), isError: true);
        }

        public void OnAbout(IRibbonControl control)
        {
            // Engine version: <root>\engine\VERSION.txt under the add-in's layout
            // (build_pack writes the build stamp into the packed copy).
            var engineVersion = "Unknown";
            try
            {
                var versionFile = AddInLayout.FindFile(out _, "engine", "VERSION.txt");
                if (versionFile != null)
                    engineVersion = File.ReadAllText(versionFile).Trim();
            }
            catch { }

            // Technique count from the catalog the add-in actually loaded.
            var techniqueCount = 0;
            var categoryCount = 0;
            try
            {
                techniqueCount = TechniqueCatalogService.GetCatalog().Techniques.Count;
                categoryCount = TechniqueCatalogService.GetCategories().Count;
            }
            catch { }

            var techniqueInfo = techniqueCount > 0
                ? $"{techniqueCount} techniques across {categoryCount} categories"
                : "Technique catalog not found";

            // Runtime: the interpreter the engine actually uses - asked of
            // EngineClient.ResolvePythonExe (the one place it is chosen), then of
            // that interpreter itself (version + its own sys.executable).
            var pythonVersion = "Not detected";
            try
            {
                var exe = EngineClient.ResolvePythonExe();
                var psi = new ProcessStartInfo
                {
                    FileName = exe,
                    Arguments = "-c \"import platform,sys;print('Python '+platform.python_version()+' at '+sys.executable)\"",
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    CreateNoWindow = true,
                };
                using (var proc = Process.Start(psi))
                {
                    if (proc == null)
                        pythonVersion = $"could not start {exe}";
                    else if (!proc.WaitForExit(5000))
                    {
                        try { proc.Kill(); } catch { }
                        pythonVersion = $"no answer within 5 s from {exe}";
                    }
                    else
                        pythonVersion = proc.StandardOutput.ReadToEnd().Trim();
                }
            }
            catch (FileNotFoundException ex)
            {
                pythonVersion = "not found: " + (ex.FileName ?? "the engine's Python runtime could not be located");
            }
            catch (Exception ex)
            {
                pythonVersion = "not detected (" + ex.Message + ")";
            }

            // This Excel's own engine (A2: one engine per Excel instance).
            var engineStatus = AddIn.Engine?.StatusText ?? "Not running";

            HouseDialog.ShowHouseAlert(AboutBox.Text(BuildInfo.Stamp, engineVersion, engineStatus, techniqueInfo,
                    pythonVersion, AddInLayout.KindLabel, AddInLayout.Root, AddIn.AppDataPath),
                HouseDialog.AboutCaption);
        }

        #endregion
    }

    /// <summary>
    /// The About box text (docs/HOUSE_STYLE.md, About box; A2 U5). Pure and apart from the
    /// Ribbon class (whose Excel-DNA base type needs Excel), so it can be exercised outside Excel.
    /// </summary>
    internal static class AboutBox
    {
        /// <summary>
        /// The product, the build line "Build &lt;describe&gt; / &lt;yyyy-MM-dd HH:mm&gt;", author,
        /// copyright, tagline and the Global Macro Charts line, then the diagnostics block,
        /// one "Label: value" line each (ratification Q4), in three groups separated by a blank
        /// line: engine, platform, layout (E2a rulings, 2026-10-03). The copyright sign (U+00A9)
        /// is the one permitted non-ASCII character.
        /// </summary>
        internal static string Text(string stamp, string engineVersion, string engineStatus,
            string techniqueLibrary, string runtime, string layoutKind, string layoutRoot, string appDataPath)
        {
            return "Time Series Lab\n\n" +
                   $"Build {stamp}\n" +
                   "Created by Matthew Hornbach\n" +
                   "\u00A9 2026 All Rights Reserved\n\n" +
                   "Macro-finance time-series analysis add-in\n" +
                   "for Microsoft Excel 365 Desktop (Windows)\n\n" +
                   "Also by Matthew Hornbach: Global Macro Charts\n\n" +
                   $"Engine version: {HouseDialog.Ascii(engineVersion)}\n" +
                   $"Engine status: {engineStatus}\n" +
                   $"Technique library: {techniqueLibrary}\n\n" +
                   "Platform: .NET Framework 4.8 + Excel-DNA\n" +
                   $"Runtime: {HouseDialog.Ascii(runtime)}\n" +
                   "Compute: 100% local (no cloud, no telemetry)\n\n" +
                   $"Layout: {layoutKind} at {layoutRoot ?? "(files not located)"}\n" +
                   $"Settings: {Path.Combine(appDataPath, "config.json")}\n" +
                   $"Logs: {Path.Combine(appDataPath, "logs")}";
        }
    }
}
