using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using ExcelDna.Integration;
using ExcelDna.Integration.CustomUI;
using Microsoft.Office.Interop.Excel;
using Application = Microsoft.Office.Interop.Excel.Application;

namespace TSL.AddIn
{
    /// <summary>
    /// Office IRibbonExtensibility COM interface.
    /// Defined locally to avoid depending on the Office PIA (office.dll).
    /// </summary>
    [ComImport]
    [Guid("000C0396-0000-0000-C000-000000000046")]
    [InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    internal interface IRibbonExtensibility
    {
        [DispId(1)]
        string GetCustomUI(string ribbonId);
    }

    /// <summary>
    /// Ribbon controller for the "Time Series Lab" tab.
    /// Uses ExcelComAddIn (not ExcelRibbon) to avoid Excel-DNA auto-discovery,
    /// which would register the ribbon before external COM add-ins (e.g. Acrobat).
    /// Manually registered via ExcelComAddInHelper.LoadComAddIn() in AddIn.AutoOpen().
    /// </summary>
    [ComVisible(true)]
    public class Ribbon : ExcelComAddIn, IRibbonExtensibility
    {
        private ExcelDna.Integration.CustomUI.IRibbonUI _ribbonUi;

        // Technique id -> sample dataset file + sheet name. Populated from
        // the catalog + a curated mapping of each technique to the most
        // appropriate data. Drives the per-technique Sample Data submenu
        // (one entry per technique, grouped by category).
        // GENERATED by tools/.../generate_sample_menu.py — keep the
        // entries in sync with the Ribbon XML if you add new techniques.
        private static readonly System.Collections.Generic.Dictionary<string, (string CsvFileName, string SheetName)>
            _sampleDatasetByTechnique =
                new System.Collections.Generic.Dictionary<string, (string, string)>(System.StringComparer.OrdinalIgnoreCase)
                {
                    { "stl_decompose", ("airline_passengers.csv", "Airline Passengers") },
                    { "classical_decompose", ("airline_passengers.csv", "Airline Passengers") },
                    { "mstl_decompose", ("airline_passengers.csv", "Airline Passengers") },
                    { "x13_seasonal_adjust", ("nonfarm_payroll_nsa.csv", "Payrolls NSA") },
                    { "ets_hw", ("airline_passengers.csv", "Airline Passengers") },
                    { "theta_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "arima", ("real_gdp.csv", "Real GDP") },
                    { "sarima", ("airline_passengers.csv", "Airline Passengers") },
                    { "auto_arima", ("airline_passengers.csv", "Airline Passengers") },
                    { "arimax_sarimax", ("macro_var.csv", "Macro VAR") },
                    { "transfer_function", ("macro_var.csv", "Macro VAR") },
                    { "intermittent_demand", ("intermittent_demand.csv", "Intermittent Demand") },
                    { "adf_test", ("real_gdp.csv", "Real GDP") },
                    { "kpss_test", ("real_gdp.csv", "Real GDP") },
                    { "pp_test", ("real_gdp.csv", "Real GDP") },
                    { "var", ("macro_var.csv", "Macro VAR") },
                    { "vecm", ("treasury_yields.csv", "Treasury Yields") },
                    { "johansen_cointegration", ("treasury_yields.csv", "Treasury Yields") },
                    { "bvar", ("macro_var.csv", "Macro VAR") },
                    { "dynamic_factor_model", ("dfm_coincident.csv", "DFM Data") },
                    { "pca_analysis", ("treasury_yields.csv", "Treasury Yields") },
                    { "forecast_reconciliation", ("macro_var.csv", "Macro VAR") },
                    { "local_level", ("nile_river.csv", "Nile River") },
                    { "local_linear_trend", ("airline_passengers.csv", "Airline Passengers") },
                    { "structural_ts", ("airline_passengers.csv", "Airline Passengers") },
                    { "particle_filter", ("nile_river.csv", "Nile River") },
                    { "markov_switching", ("real_gdp.csv", "Real GDP") },
                    { "hmm", ("real_gdp.csv", "Real GDP") },
                    { "tar_setar", ("real_gdp.csv", "Real GDP") },
                    { "star", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "nar_narx", ("macro_var.csv", "Macro VAR") },
                    { "garch", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "gjr_garch", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "egarch", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "stochastic_volatility", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "har_rv", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "evt_pot_gpd", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "caviar_quantile_dynamics", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "fft_spectrum", ("sunspots.csv", "Sunspots") },
                    { "periodogram_spectral_density", ("sunspots.csv", "Sunspots") },
                    { "lomb_scargle", ("sunspots.csv", "Sunspots") },
                    { "wavelet_transform", ("sunspots.csv", "Sunspots") },
                    { "wavelet_coherence_phase_lag", ("macro_var.csv", "Macro VAR") },
                    { "ssa", ("sunspots.csv", "Sunspots") },
                    { "emd_hht", ("sunspots.csv", "Sunspots") },
                    { "pelt_change_points", ("nile_river.csv", "Nile River") },
                    { "bocpd", ("nile_river.csv", "Nile River") },
                    { "cusum_page_hinkley", ("nile_river.csv", "Nile River") },
                    { "stl_esd_anomaly", ("airline_passengers.csv", "Airline Passengers") },
                    { "intervention_analysis", ("nile_river.csv", "Nile River") },
                    { "granger_causality", ("macro_var.csv", "Macro VAR") },
                    { "cross_correlation_lag", ("macro_var.csv", "Macro VAR") },
                    { "prewhitened_ccf_lag", ("macro_var.csv", "Macro VAR") },
                    { "gcc_phat_delay", ("macro_var.csv", "Macro VAR") },
                    { "rolling_ccf_lag", ("macro_var.csv", "Macro VAR") },
                    { "dtw_alignment_lag", ("macro_var.csv", "Macro VAR") },
                    { "rolling_origin_cv", ("real_gdp.csv", "Real GDP") },
                    { "block_bootstrap", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "conformal_intervals", ("real_gdp.csv", "Real GDP") },
                    { "forecast_combination", ("real_gdp.csv", "Real GDP") },
                    { "robust_estimators", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "kalman_imputation", ("airline_passengers.csv", "Airline Passengers") },
                    { "loess_interpolation", ("airline_passengers.csv", "Airline Passengers") },
                    { "denton_chowlin_disaggregation", ("gdp_ip_disaggregation.csv", "GDP + IP") },
                    { "gradient_boosting_forecast", ("macro_var.csv", "Macro VAR") },
                    { "quantile_regression", ("real_gdp.csv", "Real GDP") },
                    { "gaussian_process_forecast", ("real_gdp.csv", "Real GDP") },
                    { "lstm_gru_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "tcn_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "nbeats_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "transformer_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "prophet_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "random_forest_forecast", ("macro_var.csv", "Macro VAR") },
                    { "xgboost_forecast", ("macro_var.csv", "Macro VAR") },
                    { "svr_forecast", ("real_gdp.csv", "Real GDP") },
                    { "autoencoder_anomaly", ("sp500_returns.csv", "S&P 500 Returns") },
                    { "nhits_forecast", ("airline_passengers.csv", "Airline Passengers") },
                    { "echo_state_network", ("sunspots.csv", "Sunspots") },
                    { "lightgbm_forecast", ("macro_var.csv", "Macro VAR") },
                };

        public string GetCustomUI(string ribbonId)
        {
            return RibbonXml.GetXml();
        }

        #region Callbacks

        public void OnRibbonLoad(IRibbonUI ribbonUi)
        {
            _ribbonUi = ribbonUi;
        }

        // ── Quick Actions ──────────────────────────────────────────────

        // ── Quick Actions: one-click run ───────────────────────────────
        // Each ribbon Quick Action skips the Explorer description page
        // and calls RunTechnique so the analysis kicks off immediately
        // against the current Excel selection. The Task Pane lands on
        // the Run view with the series preview and progress log already
        // populated.

        // Multivariate / system modeling
        public void OnVar(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("var");
        }

        public void OnPcaAnalysis(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("pca_analysis");
        }

        public void OnDynamicFactorModel(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("dynamic_factor_model");
        }

        public void OnCointegration(IRibbonControl control)
        {
            // VECM includes the Johansen cointegration test as part of
            // the fit, so landing here gives both the equilibrium test
            // and the error-correction model in one shot.
            TaskPaneManager.RunTechnique("vecm");
        }

        // Univariate workhorses + causality/forecasting
        public void OnGrangerCausality(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("granger_causality");
        }

        public void OnRollingCcf(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("rolling_ccf_lag");
        }

        public void OnSeasonalAdjustment(IRibbonControl control)
        {
            // STL is the default — robust, handles outliers, no external
            // binary required. X-13 ARIMA-SEATS is available via the
            // Technique Explorer or Sample Data menu for the BLS/BEA
            // gold-standard seasonal adjustment.
            TaskPaneManager.RunTechnique("stl_decompose");
        }

        public void OnForecast(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("auto_arima");
        }

        public void OnProphet(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("prophet_forecast");
        }

        public void OnConformal(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("conformal_intervals");
        }

        // ── Bond Yield Forecast (BYF Integration Session 3) ──────────
        // Split-button dropdown with two menu items + a primary action:
        //   - Primary click on the split button = OnBondYieldForecastRun
        //     (matches Pattern A from UX spec / plan §3.2 default action).
        //   - Submenu "Open Input Template" = OnBondYieldForecastOpenTemplate
        //   - Submenu "Run Bond Yield Forecast" = OnBondYieldForecastRun
        //     (same as primary; explicit menu entry for discoverability).

        public void OnBondYieldForecastRun(IRibbonControl control)
        {
            // Bond Yield Forecast consumes a 3-sheet xlsx workbook
            // (BondYield_Macro / BondYield_Yields / BondYield_Projections)
            // referenced via ctx.params["input_workbook"], NOT the standard
            // ctx.series cell-selection contract.
            //
            // CONFIGURE-then-run: open the Run view with the curated parameters
            // (scenario / horizon / chain length / prior tightness) pre-filled
            // and editable. The user reviews/edits, then clicks Run IN THE VIEW.
            // The Run button routes to TaskPaneManager.OnWorkbookRunRequested,
            // which resolves the active workbook, SaveCopyAs-es a local %TEMP%
            // copy (off OneDrive, captures unsaved edits — the d923c6a fix), and
            // dispatches. The "no workbook open" guard now lives at Run-click
            // (where the workbook is actually needed), not at view-open.
            try
            {
                TaskPaneManager.OpenBondYieldForecastConfig();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Error opening Bond Yield Forecast: {ex.Message}",
                    "Time Series Lab",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        public void OnBondYieldForecastOpenTemplate(IRibbonControl control)
        {
            try
            {
                var templatePath = LocateBondYieldForecastTemplate();
                if (templatePath == null)
                {
                    MessageBox.Show(
                        "Bond Yield Forecast input template not found.\n\n" +
                        "Reinstall Time Series Lab to restore the template, or " +
                        "regenerate it via:\n" +
                        "    python engine/techniques/bond_yield_forecast/" +
                        "_session3_template_generator.py\n",
                        "Time Series Lab",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);
                    return;
                }

                ExcelAsyncUtil.QueueAsMacro(() =>
                {
                    var app = (Application)ExcelDnaUtil.Application;
                    // Open as a NEW workbook (not Read-only) so the user can
                    // edit the template and save-as their own workbook before
                    // running the forecast. The unified-workbook reader doesn't
                    // require write access; opening read-write here is a UX
                    // affordance, not an engine requirement.
                    app.Workbooks.Open(templatePath, ReadOnly: false);
                });
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Error opening Bond Yield Forecast input template: {ex.Message}",
                    "Time Series Lab",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        /// <summary>
        /// Resolve the bundled Bond Yield Forecast input template path.
        /// Mirrors the LoadSampleData two-step search (dev → installed)
        /// for consistency with TSL's existing resource-bundling pattern.
        /// </summary>
        private string LocateBondYieldForecastTemplate()
        {
            const string templateRel =
                @"engine\techniques\bond_yield_forecast\resources\templates\bond_yield_forecast_input_template.xlsx";

            // Dev / project location: walk up from XLL output dir to
            // repo root. XLL is at:
            //   src/TSL.AddIn/bin/x64/Release/net48/   (6 levels up)
            // Same convention LoadSampleData uses.
            var xllDir = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
            if (!string.IsNullOrEmpty(xllDir))
            {
                var projectRoot = Path.GetFullPath(
                    Path.Combine(xllDir, "..", "..", "..", "..", "..", ".."));
                var devPath = Path.Combine(projectRoot, templateRel);
                if (File.Exists(devPath)) return devPath;
            }

            // Installed location: %LOCALAPPDATA%/TimeSeriesLab/...
            var installedPath = Path.Combine(AddIn.AppDataPath, templateRel);
            if (File.Exists(installedPath)) return installedPath;

            return null;
        }

        // Regime / volatility / state-space
        public void OnMarkovSwitching(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("markov_switching");
        }

        public void OnChangePoint(IRibbonControl control)
        {
            // PELT is the offline change-point workhorse. BOCPD (online)
            // is available via the Technique Explorer for streaming use.
            TaskPaneManager.RunTechnique("pelt_change_points");
        }

        public void OnGarch(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("garch");
        }

        public void OnStructuralTS(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("structural_ts");
        }

        // ── Legacy Quick Action handlers ──────────────────────────────
        // The Lead-Lag Finder and Anomaly Scan buttons were removed from
        // the ribbon in the macro-strategist reorg (both techniques are
        // still available via the Technique Explorer and Sample Data
        // menu). Handler stubs remain so any saved macros or legacy
        // workflows referencing them by name keep working.
        public void OnLeadLagFinder(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("prewhitened_ccf_lag");
        }

        public void OnAnomalyScan(IRibbonControl control)
        {
            TaskPaneManager.RunTechnique("stl_esd_anomaly");
        }

        // ── Explore ────────────────────────────────────────────────────

        public void OnTechniqueExplorer(IRibbonControl control)
        {
            TaskPaneManager.ShowExplorer();
        }

        public void OnRecommenderWizard(IRibbonControl control)
        {
            TaskPaneManager.ShowRecommender();
        }

        public void OnRecommenderGoal(IRibbonControl control)
        {
            TaskPaneManager.ShowRecommenderWithGoal(control.Tag);
        }

        public void OnExplorerCategory(IRibbonControl control)
        {
            TaskPaneManager.ShowExplorerWithCategory(control.Tag);
        }

        public void OnDataReadiness(IRibbonControl control)
        {
            TaskPaneManager.ShowDataReadiness();
        }

        // ── Run ────────────────────────────────────────────────────────

        /// <summary>
        /// Menu-level label for the Preset button. Shows "Preset: <current>"
        /// so the user sees their active selection without having to open the
        /// menu.
        /// </summary>
        public string OnPresetGetLabel(IRibbonControl control)
        {
            var preset = AddIn.Settings?.GetGlobalPreset() ?? "Balanced";
            return $"Preset: {preset}";
        }

        /// <summary>
        /// Returns true for the toggleButton whose tag matches the currently
        /// active preset. Excel renders the matching item with a check mark
        /// in the menu (just like "None (House Default)" in the Axes Grid
        /// reference menu).
        /// </summary>
        public bool OnPresetGetPressed(IRibbonControl control)
        {
            var current = AddIn.Settings?.GetGlobalPreset() ?? "Balanced";
            return string.Equals(control?.Tag, current, StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Click handler for the three preset toggleButtons. Pulls the
        /// preset name from the control's Tag attribute.
        /// </summary>
        public void OnPresetMenuClick(IRibbonControl control, bool pressed)
        {
            var preset = control?.Tag;
            if (string.IsNullOrEmpty(preset)) return;

            AddIn.Settings?.SetGlobalPreset(preset);
            TaskPaneManager.UpdatePreset(preset);

            // Refresh the menu button label and the check marks on the
            // three toggle buttons so the UI reflects the new selection.
            _ribbonUi?.InvalidateControl("menuPreset");
            _ribbonUi?.InvalidateControl("btnPresetFast");
            _ribbonUi?.InvalidateControl("btnPresetBalanced");
            _ribbonUi?.InvalidateControl("btnPresetThorough");
        }

        public void OnRun(IRibbonControl control)
        {
            TaskPaneManager.RunCurrent();
        }

        public void OnCancel(IRibbonControl control)
        {
            AddIn.Engine?.CancelCurrentRun();
        }

        public void OnRerunThorough(IRibbonControl control)
        {
            TriggerManager.IncrementTrigger();
            _ribbonUi?.Invalidate();
        }

        public void OnSettings(IRibbonControl control)
        {
            TaskPaneManager.ShowSettings();
        }

        // ── Help ───────────────────────────────────────────────────────

        public void OnUdfGuide(IRibbonControl control)
        {
            TaskPaneManager.ShowUdfBrowser();
        }

        public void OnOpenUserGuide(IRibbonControl control)
        {
            // Check installed location first
            var guidePath = Path.Combine(AddIn.AppDataPath, "docs", "TimeSeriesLab_UserGuide.docx");

            // Fallback: dev/project location (navigate up from XLL output dir)
            // XLL is at: src/TSL.AddIn/bin/x64/Release/net48/ — 6 levels up to project root
            if (!File.Exists(guidePath))
            {
                var xllDir = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
                var projectRoot = Path.GetFullPath(Path.Combine(xllDir, "..", "..", "..", "..", "..", ".."));
                guidePath = Path.Combine(projectRoot, "docs", "TimeSeriesLab_UserGuide.docx");
            }

            if (File.Exists(guidePath))
            {
                Process.Start(guidePath);
            }
            else
            {
                // Offer to generate it
                var result = MessageBox.Show(
                    "User Guide has not been generated yet.\n\n" +
                    "Would you like to generate it now?\n" +
                    "(Requires Python with python-docx installed)",
                    "Time Series Lab",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question);

                if (result == DialogResult.Yes)
                {
                    try
                    {
                        var xllDir = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
                        var projectRoot = Path.GetFullPath(Path.Combine(xllDir, "..", "..", "..", "..", "..", ".."));
                        var script = Path.Combine(projectRoot, "tools", "generate_user_guide.py");
                        if (File.Exists(script))
                        {
                            var psi = new ProcessStartInfo
                            {
                                FileName = "python",
                                Arguments = $"\"{script}\"",
                                WorkingDirectory = projectRoot,
                                UseShellExecute = false,
                                CreateNoWindow = true,
                            };
                            using (var proc = Process.Start(psi))
                            {
                                proc?.WaitForExit(30000);
                            }

                            var generated = Path.Combine(projectRoot, "docs", "TimeSeriesLab_UserGuide.docx");
                            if (File.Exists(generated))
                                Process.Start(generated);
                            else
                                MessageBox.Show("Generation completed but the file was not created.\nCheck the tools/generate_user_guide.py script.",
                                    "Time Series Lab", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                        }
                        else
                        {
                            MessageBox.Show($"Generator script not found at:\n{script}",
                                "Time Series Lab", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                        }
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show($"Failed to generate User Guide:\n{ex.Message}",
                            "Time Series Lab", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
        }

        public void OnOpenUserGuideHtml(IRibbonControl control)
        {
            // Check installed location first
            var guidePath = Path.Combine(AddIn.AppDataPath, "docs", "TimeSeriesLab_UserGuide.html");

            // Fallback: dev/project location
            if (!File.Exists(guidePath))
            {
                var xllDir = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
                var projectRoot = Path.GetFullPath(Path.Combine(xllDir, "..", "..", "..", "..", "..", ".."));
                guidePath = Path.Combine(projectRoot, "docs", "TimeSeriesLab_UserGuide.html");
            }

            if (File.Exists(guidePath))
            {
                Process.Start(guidePath);
            }
            else
            {
                MessageBox.Show(
                    "HTML User Guide not found.\n\n" +
                    "Run tools\\generate_user_guide.py to generate it.",
                    "Time Series Lab",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Warning);
            }
        }

        /// <summary>
        /// Single handler for all 81 per-technique sample-data menu entries.
        /// Reads the clicked button's `tag` (the technique id) and looks up
        /// the matching CSV + sheet name in `_sampleDatasetByTechnique`.
        /// Many techniques share the same CSV — that's fine; each technique
        /// gets its own labelled entry, and they all land on a fresh sheet
        /// (unique-ified if the target name already exists).
        /// </summary>
        public void OnSampleDataByTechnique(IRibbonControl control)
        {
            var tid = control?.Tag;
            if (string.IsNullOrEmpty(tid))
            {
                MessageBox.Show("Sample-data button has no technique tag.",
                    "Time Series Lab", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            if (!_sampleDatasetByTechnique.TryGetValue(tid, out var mapping))
            {
                MessageBox.Show(
                    $"No sample dataset registered for technique '{tid}'.\n\n" +
                    "This is a bug — the ribbon XML includes a technique that " +
                    "isn't in the sample-data mapping. Please report.",
                    "Time Series Lab", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            LoadSampleData(mapping.CsvFileName, mapping.SheetName);
        }

        public void OnSampleDataTreasury(IRibbonControl control)
        {
            LoadSampleData("treasury_yields.csv", "Treasury Yields");
        }

        public void OnSampleDataGdp(IRibbonControl control)
        {
            LoadSampleData("real_gdp.csv", "Real GDP");
        }

        public void OnSampleDataPce(IRibbonControl control)
        {
            LoadSampleData("core_pce.csv", "Core PCE");
        }

        public void OnSampleDataPayrollSa(IRibbonControl control)
        {
            // Total nonfarm payroll employment levels, seasonally adjusted
            // (FRED PAYEMS, in thousands of jobs). Coverage: Jan 1939 -> latest.
            // Levels — not differences — so X-13/STL seasonal decomposition
            // produces the textbook SA series; compute job gains downstream
            // as first differences of the SA column if desired.
            LoadSampleData("nonfarm_payroll_sa.csv", "Payrolls SA");
        }

        public void OnSampleDataPayrollNsa(IRibbonControl control)
        {
            // Total nonfarm payroll employment levels, not seasonally adjusted
            // (FRED PAYNSA, in thousands of jobs). Coverage: Jan 1939 -> latest.
            // Levels series suitable as direct X-13 / STL input.
            LoadSampleData("nonfarm_payroll_nsa.csv", "Payrolls NSA");
        }

        public void OnSampleDataDfm(IRibbonControl control)
        {
            // Stock-Watson (1989) four coincident indicators: the canonical
            // DFM input and the same series NBER uses for business-cycle
            // dating. Industrial Production (INDPRO), Nonfarm Payrolls
            // (PAYEMS), Real Disposable Personal Income ex. Transfers
            // (W875RX1), Real Manufacturing and Trade Sales (CMRMTSPL).
            // Common window: Jan 1967 -> latest (~709 months).
            LoadSampleData("dfm_coincident.csv", "DFM Data");
        }

        private void LoadSampleData(string fileName, string sheetName)
        {
            try
            {
                // Locate the CSV file
                string csvPath = null;

                // Try dev/project location
                var xllDir = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
                var projectRoot = Path.GetFullPath(Path.Combine(xllDir, "..", "..", "..", "..", "..", ".."));
                var devPath = Path.Combine(projectRoot, "resources", "sample_data", fileName);
                if (File.Exists(devPath))
                    csvPath = devPath;

                // Fallback: installed location
                if (csvPath == null)
                {
                    var installedPath = Path.Combine(AddIn.AppDataPath, "sample_data", fileName);
                    if (File.Exists(installedPath))
                        csvPath = installedPath;
                }

                if (csvPath == null)
                {
                    MessageBox.Show(
                        $"Sample data file not found: {fileName}\n\n" +
                        "Reinstall Time Series Lab to restore the sample data files.",
                        "Time Series Lab",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);
                    return;
                }

                // Read CSV and write to a new worksheet
                ExcelAsyncUtil.QueueAsMacro(() =>
                {
                    var app = (Microsoft.Office.Interop.Excel.Application)ExcelDnaUtil.Application;
                    var wb = app.ActiveWorkbook ?? app.Workbooks.Add();
                    var ws = (Microsoft.Office.Interop.Excel.Worksheet)wb.Worksheets.Add();

                    // Make the sheet name unique. With per-technique sample
                    // data entries many techniques share a CSV (e.g. STL,
                    // Classical Decomp, ETS, ARIMA, SARIMA, etc. all load
                    // "Airline Passengers"). If the user clicks two such
                    // entries, the second would otherwise fail with Excel's
                    // "sheet name already in use" error.
                    string candidateName = sheetName;
                    int suffix = 2;
                    bool Exists(string n)
                    {
                        foreach (Microsoft.Office.Interop.Excel.Worksheet s in wb.Worksheets)
                            if (string.Equals(s.Name, n, StringComparison.OrdinalIgnoreCase) && s != ws)
                                return true;
                        return false;
                    }
                    while (Exists(candidateName))
                    {
                        candidateName = $"{sheetName} ({suffix})";
                        suffix++;
                    }
                    ws.Name = candidateName;

                    var lines = File.ReadAllLines(csvPath);
                    for (int r = 0; r < lines.Length; r++)
                    {
                        var cells = lines[r].Split(',');
                        for (int c = 0; c < cells.Length; c++)
                        {
                            var val = cells[c].Trim();
                            ((Range)ws.Cells[r + 1, c + 1]).Value2 = val;
                        }
                    }

                    // Auto-fit columns
                    ws.Columns.AutoFit();
                    ws.Activate();
                });
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Error loading sample data: {ex.Message}",
                    "Time Series Lab",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        public void OnSaveInstaller(IRibbonControl control)
        {
            try
            {
                // Locate the installer pack directory
                // Installed: %LOCALAPPDATA%\TimeSeriesLab  (the install itself IS the pack)
                // Dev: <project_root>\build\pack
                string packDir = null;

                // Try dev/project location first
                var xllDir = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
                var projectRoot = Path.GetFullPath(Path.Combine(xllDir, "..", "..", "..", "..", "..", ".."));
                var devPack = Path.Combine(projectRoot, "build", "pack");
                if (Directory.Exists(devPack) && File.Exists(Path.Combine(devPack, "TSL.Installer.exe")))
                {
                    packDir = devPack;
                }

                // Fallback: installed location (AppData has the same structure)
                if (packDir == null && Directory.Exists(AddIn.AppDataPath)
                    && File.Exists(Path.Combine(AddIn.AppDataPath, "TSL.Installer.exe")))
                {
                    packDir = AddIn.AppDataPath;
                }

                if (packDir == null)
                {
                    MessageBox.Show(
                        "Installer package not found.\n\n" +
                        "Run tools\\build_pack.ps1 from the project root to create it,\n" +
                        "or reinstall Time Series Lab to restore the installer files.",
                        "Time Series Lab",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning);
                    return;
                }

                // Open a folder browser so the user picks a destination
                using (var dialog = new FolderBrowserDialog())
                {
                    dialog.Description = "Choose a folder to save the Time Series Lab installer package.";
                    dialog.ShowNewFolderButton = true;

                    if (dialog.ShowDialog() != DialogResult.OK)
                        return;

                    var destDir = Path.Combine(dialog.SelectedPath, "TimeSeriesLab_Installer");

                    if (Directory.Exists(destDir))
                    {
                        var overwrite = MessageBox.Show(
                            $"'{destDir}' already exists.\n\nOverwrite it?",
                            "Time Series Lab",
                            MessageBoxButtons.YesNo,
                            MessageBoxIcon.Question);
                        if (overwrite != DialogResult.Yes)
                            return;
                        Directory.Delete(destDir, true);
                    }

                    // Recursive copy
                    CopyDirectory(packDir, destDir);

                    MessageBox.Show(
                        $"Installer package saved to:\n{destDir}\n\n" +
                        "To install on another PC, copy this folder and run TSL.Installer.exe.",
                        "Time Series Lab",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Information);

                    // Open the destination folder in Explorer
                    Process.Start("explorer.exe", destDir);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to save installer package:\n{ex.Message}",
                    "Time Series Lab",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private static void CopyDirectory(string sourceDir, string destDir)
        {
            Directory.CreateDirectory(destDir);

            foreach (var file in Directory.GetFiles(sourceDir))
            {
                var destFile = Path.Combine(destDir, Path.GetFileName(file));
                File.Copy(file, destFile, true);
            }

            foreach (var dir in Directory.GetDirectories(sourceDir))
            {
                var destSub = Path.Combine(destDir, Path.GetFileName(dir));
                CopyDirectory(dir, destSub);
            }
        }

        public void OnAbout(IRibbonControl control)
        {
            var addinVersion = typeof(Ribbon).Assembly.GetName().Version;

            // Read engine version from VERSION.txt (try project dir first, then AppData)
            var engineVersion = "Unknown";
            try
            {
                var xllDir = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
                var projectRoot = Path.GetFullPath(Path.Combine(xllDir, "..", "..", "..", "..", "..", ".."));
                var versionFile = Path.Combine(projectRoot, "engine", "VERSION.txt");
                if (!File.Exists(versionFile))
                    versionFile = Path.Combine(AddIn.AppDataPath, "engine", "VERSION.txt");
                if (File.Exists(versionFile))
                    engineVersion = File.ReadAllText(versionFile).Trim();
            }
            catch { }

            // Count techniques from catalog
            var techniqueCount = 0;
            var categoryCount = 0;
            try
            {
                var xllDir = Path.GetDirectoryName(ExcelDnaUtil.XllPath);
                var projectRoot = Path.GetFullPath(Path.Combine(xllDir, "..", "..", "..", "..", "..", ".."));
                var catalogPath = Path.Combine(projectRoot, "resources", "catalog", "techniques_catalog.json");
                if (File.Exists(catalogPath))
                {
                    var json = File.ReadAllText(catalogPath);
                    // Simple count: occurrences of "\"id\":" for techniques
                    techniqueCount = System.Text.RegularExpressions.Regex.Matches(json, "\"id\"\\s*:").Count;
                    // Count unique categories
                    var catMatches = System.Text.RegularExpressions.Regex.Matches(json, "\"category\"\\s*:\\s*\"([^\"]+)\"");
                    var cats = new System.Collections.Generic.HashSet<string>();
                    foreach (System.Text.RegularExpressions.Match m in catMatches)
                        cats.Add(m.Groups[1].Value);
                    categoryCount = cats.Count;
                }
            }
            catch { }

            var techniqueInfo = techniqueCount > 0
                ? $"{techniqueCount} techniques across {categoryCount} categories"
                : "Technique catalog not found";

            // Detect Python version
            var pythonVersion = "Not detected";
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "python",
                    Arguments = "--version",
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    CreateNoWindow = true,
                };
                using (var proc = Process.Start(psi))
                {
                    if (proc != null)
                    {
                        pythonVersion = proc.StandardOutput.ReadToEnd().Trim();
                        proc.WaitForExit(3000);
                    }
                }
            }
            catch { }

            // Check if engine pipe exists (engine is running)
            var engineStatus = "Not running";
            try
            {
                var sid = System.Security.Principal.WindowsIdentity.GetCurrent().User?.Value ?? "default";
                var pipeName = $"TSL_ENGINE_PIPE_{sid}";
                if (File.Exists($@"\\.\pipe\{pipeName}"))
                    engineStatus = "Running";
            }
            catch { }

            MessageBox.Show(
                $"Time Series Lab\n" +
                $"Created by Matthew T. Hornbach\n\n" +
                $"Add-in version:    {addinVersion}\n" +
                $"Engine version:    {engineVersion}\n" +
                $"Engine status:     {engineStatus}\n" +
                $"Technique library: {techniqueInfo}\n\n" +
                $"Platform:          .NET Framework 4.8 + Excel-DNA\n" +
                $"Runtime:           {pythonVersion}\n" +
                $"Compute:           100% local (no cloud, no telemetry)\n\n" +
                $"Project:           {Path.GetDirectoryName(Path.GetDirectoryName(Path.GetDirectoryName(Path.GetDirectoryName(Path.GetDirectoryName(Path.GetDirectoryName(ExcelDnaUtil.XllPath))))))}\n" +
                $"Settings:          {Path.Combine(AddIn.AppDataPath, "config.json")}\n" +
                $"Logs:              {Path.Combine(AddIn.AppDataPath, "logs")}",
                "About Time Series Lab",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information);
        }

        #endregion
    }
}
